/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jniexample_MainActivity */

#ifndef _Included_com_jniexample_MainActivity
#define _Included_com_jniexample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jniexample_MainActivity
 * Method:    helloWorld
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jniexample_MainActivity_helloWorld
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
